# Generated by Django 4.0.3 on 2022-04-06 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='Todo_text',
            new_name='todo_text',
        ),
        migrations.AlterField(
            model_name='todo',
            name='due_date',
            field=models.DateField(null=True, verbose_name='due date'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
