# Generated by Django 4.0.3 on 2022-04-07 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_todo_text_todo_todo_text_alter_todo_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_text',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
